version: '2.1'

services:
  api:
    build: .
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_NAME: test
      DB_HOSTNAME: db
    command: ["npm", "run", "migrate"]
    ports:
      - 3000:3000
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: 'test'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data:
